import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";

import UserContextProvider from "@/context/UserContext";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const req = await fetch("http://localhost:3000/api/currentUser");
  const initialUser = await req.json();

  return (
    <html lang="en">
      <body className={jost.className}>
        <UserContextProvider initialUser={initialUser}>
          <main className="max-w-6xl m-auto lg:my-16 lg:px-8">{children}</main>
        </UserContextProvider>
      </body>
    </html>
  );
}
