import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";

// import { Providers } from "@/store/provider";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        {/* <Providers> */}
          <main className="max-w-6xl m-auto lg:my-16 lg:px-8">{children}</main>
        {/* </Providers> */}
      </body>
    </html>
  );
}
